sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t chuck4637/docker-react-app .

script:
  - docker run -e CI=true chuck4637/docker-react-app

deploy:
  provider: elasticbeanstalk
  region: $AWS_REGION
  app: "docker-react-app"
  env: $AWS_ENV
  bucket_name: $AWS_BUCKET_NAME
  bucket_path: $AWS_BUCKET_PATH
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET
